Update 27126_test.yml

diff --git a/.github/workflows/27126_test.yml b/.github/workflows/27126_test.yml
--- a/.github/workflows/27126_test.yml
+++ b/.github/workflows/27126_test.yml
@@ -25,10 +25,8 @@ jobs:
 
     - name: Run tests
       run: |
-        python test_script.py || echo "Test failed" > napaka.txt
+        python main.py || echo "Test failed" > napaka.txt
 
     - name: Check for errors
       if: failure()
       run: cat napaka.txt
-
-
