Update 27126_test.yml

diff --git a/.github/workflows/27126_test.yml b/.github/workflows/27126_test.yml
--- a/.github/workflows/27126_test.yml
+++ b/.github/workflows/27126_test.yml
@@ -23,7 +23,7 @@ jobs:
 
     - name: Run tests and capture output
       run: |
-        python main.py > test_output.txt || echo "Test failed" > napaka.txt
+        python test_main.py > test_output.txt || echo "Test failed" > napaka.txt
 
     - name: Check for errors
       run: |
